name: Test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.39.0/ktlint
          chmod a+x ktlint
          ./ktlint "**/src/**/*.kt" --color --relative

      - name: Test
        run: ./gradlew test
